name: Hello World on Main

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout second repo
        uses: actions/checkout@v4
        with:
          repository: steinertech/steinertech.github.io
          path: pages
          token: ${{ secrets.PAGES_PAT }}

      - name: Make script executable
        run: chmod +x .github/workflows/hello.sh

      - name: Run Hello World Script
        run: .github/workflows/hello.sh

