name: Hello World on Main

on:
  push:
    branches:
      - main

permissions:
  contents: write
  
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x .github/workflows/hello.sh

      - name: Run Hello World Script
        run: .github/workflows/hello.sh

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: App.Web/dist  # or your build output directory

      - name: Deploy to external repo
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }} # See also https://github.com/settings/personal-access-tokens and https://github.com/steinertech/Test/settings/secrets/actions 
          external_repository: steinertech/steinertech.github.io
          publish_branch: gh-pages
          publish_dir: App.Web/dist
